import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/layout/header";
import { SpeedInsights } from "@vercel/speed-insights/next";
import AuthenticationProvider from "@/components/authentication/authentication-provider";
import { Bounce, ToastContainer } from "react-toastify";
import Footer from "@/components/layout/footer";
import Head from "next/head";
import { FontSizeProvider } from "@/context/font-size-context";
import { ColorModeProvider } from "@/context/color-mode-context";
import { Analytics } from "@vercel/analytics/next";
import "@stream-io/video-react-sdk/dist/css/styles.css";
import "react-datepicker/dist/react-datepicker.css";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Təhsildə Keyfiyyət Təminatı Agentliyi - TKTA | TKTA",
  description: "Generated by create next app",
  keywords: "azerbaijan, tehsil, keyfiyyet, agentlik, nazirlik",
};

type Params = {
  locale: string;
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<Params>;
}>) {
  const { locale } = await params;

  return (
    <html lang={locale}>
      <Head>
        <meta name="al:ios:url" content="instagram://user?username=tktaeduaz" />
        <meta name="al:ios:app_name" content="Instagram" />
        <meta
          name="al:android:url"
          content="instagram://user?username=tktaeduaz"
        />
        <meta name="al:android:app_name" content="Instagram" />
        <meta property="al:web:url" content="https://instagram.com/tktaeduaz" />
      </Head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FontSizeProvider>
          <ColorModeProvider>
            <AuthenticationProvider>
              <Header locale={locale} />

              {children}

              <Footer />

              <SpeedInsights />

              <Analytics />
            </AuthenticationProvider>
          </ColorModeProvider>
        </FontSizeProvider>

        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={true}
          closeOnClick={true}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
          transition={Bounce}
        />
      </body>
    </html>
  );
}
