import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import { SpeedInsights } from "@vercel/speed-insights/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  video,
  services,
  statistics,
  news,
}: Readonly<{
  children: React.ReactNode;
  video: React.ReactNode;
  services: React.ReactNode;
  statistics: React.ReactNode;
  news: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />

        <main className="flex flex-col gap-20">
          <section>{video}</section>

          <section>{services}</section>

          <section>{statistics}</section>

          <section>{news}</section>

          {children}
        </main>

        <SpeedInsights />
      </body>
    </html>
  );
}
