import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import { SpeedInsights } from "@vercel/speed-insights/next";
import AuthenticationProvider from "@/components/authentication/authentication-provider";
import { Bounce, ToastContainer } from "react-toastify";
import Footer from "@/components/layout/footer";
import Head from "next/head";
import { FontSizeProvider } from "@/context/font-size-context";
import { ColorModeProvider } from "@/context/color-mode-context";
import { Analytics } from '@vercel/analytics/next';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta name="al:ios:url" content="instagram://user?username=tktaeduaz" />
        <meta name="al:ios:app_name" content="Instagram" />
        <meta
          name="al:android:url"
          content="instagram://user?username=tktaeduaz"
        />
        <meta name="al:android:app_name" content="Instagram" />
        <meta property="al:web:url" content="https://instagram.com/tktaeduaz" />
      </Head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FontSizeProvider>
          <ColorModeProvider>
            <AuthenticationProvider>
              <Header />

              {children}

              <Footer />

              <SpeedInsights />

              <Analytics />
            </AuthenticationProvider>
          </ColorModeProvider>
        </FontSizeProvider>

        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={true}
          closeOnClick={true}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
          transition={Bounce}
        />
      </body>
    </html>
  );
}
